### PR TITLE
No Price fix

### PR DESCRIPTION
**Pull request by dandud100**
They updated their class, this should fix the problem #13

### CODE REVIEW

**Review by nilsreichardt — COMMENTED** [review]
I'm not sure if you also need to update the test files in the following locations so that the tests are still working (I'm not familiar with python, so I don't know to run them properly).

* https://github.com/vinc3PO/ebayKleinanzeigenAlert/blob/master/test/test.html
* https://github.com/vinc3PO/ebayKleinanzeigenAlert/blob/master/test/test_article.html

**Comment by nilsreichardt** [comment]
Is it working for you? I implemented this fix for my local clone but I'm still getting "No Price". However, I'm also not sure if I forget something.

**Comment by daniel22-git** [comment]
> Is it working for you? I implemented this fix for my local clone but I'm still getting "No Price". However, I'm also not sure if I forget something.

I think you need to redo: `pip install .`

**Comment by nilsreichardt** [comment]
Yes, after running `pip install .` it's working :)

**Pull request merged**
