### PR TITLE
Update ebayclass.py

### LINKED ISSUE #13: No Price
Hello, on Telegram it always shows "No Price" but there is one. Could you look into this. Thanks. ✌🏻

### PR DESCRIPTION
**Pull request by dandud100**
This should fix #13

### CODE REVIEW

**Comment by nilsreichardt** [comment]
Is it correct that you started your branch from the branch of #14?

**Comment by nilsreichardt** [comment]
I think you need also to update test files:
* https://github.com/vinc3PO/ebayKleinanzeigenAlert/blob/master/test/test.html
* https://github.com/vinc3PO/ebayKleinanzeigenAlert/blob/master/test/test_article.html

**Comment by daniel22-git** [comment]
> Is it correct that you started your branch from the branch of #14?

Oh I see what I did wrong here. Why is GitHub so difficult I thought it will only keep my change to ebayclass.py here... Do you know how to exclude commits from a pull request?

**Comment by daniel22-git** [comment]
I think i need to do this with branches...

**Comment by nilsreichardt** [comment]
The easiest way would be to cherry-pick your commit to a new branch:

```sh
git checkout origin/main
git checkout -b fix-price
git cherry-pick 52037f0bb783c38bf0a265d9caac617ca5af7147
```

**Pull request closed without merging**
