### PR TITLE
2 different chats

### PR DESCRIPTION
**Pull request by Babelbernd**
Is there a possibility to send Telegramm messages to different Bots? 

I would like to have my telegram chats nice and clean 😅 

For example i would like to receive my 'Concerts' alert in a different chat than my 'BMW' alert. 

Is this possible? Thanks

### CODE REVIEW

**Comment by Babelbernd** [comment]
Thanks for this 👍

**Comment by Babelbernd** [comment]
I think i was a bit too quick when closing my request. I dont get it how to setup the multiple user. Could you explain it for dummies :-)

Regards Michael

**Comment by cyberpete2244** [comment]
I am not sure what is going on in this monologue so far. I forked this project and edited it to my needs. As far as I can tell from the code there currently is no feature to send different searches to different telegram chats. What I did was: I have a development telegram bot sending messages when i debug and I have a production tegeram bot. What I do is: using separated configs files for these two different environments.

What you woul need to do is actually modify the links table in database and add the funktions you need to save bots (ids and tokens) per search.

I did not reasearch if you actually can have two separate chats open with the same bot on telegram. It would be like having two users on telegaram chatting over different chats. I do not know if telegram does that. I suspect not.

So you would need two different bots sending you messagases for separate searches. That would populate two different chats.

Does that help?

EDIT: I am a bit new to this github stuff. As far as I understand there were commits in other branches that had featurs you wanted? I was just writing from the perspective of knowing what is in the master branch...

**Comment by Babelbernd** [comment]
Well, my target is following: I have some telegram bots, also one with your ebAlert. I told a friend about your ebAlert and she asked me if i can add another link to my ebAlert configuration, so she receives those messages? For example i have added a link about tables an i get those telegram Messages and i want to add another link about chairs which my friend will receive those telegram messages. Any idea for my problem?

**Pull request closed without merging**
